# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhr', '0007_auto_20170313_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='unblock_at',
            field=models.DateTimeField(null=True, verbose_name=b'date to be unblocked'),
        ),
        migrations.RunSQL('CREATE INDEX bhr_block_unblocked_by ON bhr_block(unblock_who_id) WHERE unblock_who_id IS NOT NULL'),
    ]
