# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhr', '0008_auto_20170314_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date added'),
        ),
    ]
