# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-30 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhr', '0009_bhr_block_added_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='unblock_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name=b'date to be unblocked'),
        ),
    ]
