# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-31 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhr', '0010_auto_20170330_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockentry',
            name='removed',
            field=models.DateTimeField(null=True, verbose_name=b'date removed'),
        ),
        migrations.RunSQL('CREATE INDEX bhr_blockentry_removed ON bhr_blockentry(removed) WHERE removed IS NULL'),
    ]
