# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhr', '0011_auto_20170531_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockentry',
            name='unblock_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name=b'date to be unblocked'),
            preserve_default=False,
        ),
        migrations.RunSQL('''UPDATE bhr_blockentry
            SET
                unblock_at = b.unblock_at
            FROM
                bhr_block AS b
            WHERE
                b.id=bhr_blockentry.block_id''')

    ]
