# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhr', '0012_blockentry_unblock_at')
    ]

    operations = [
        migrations.RunSQL('create index bhr_blockentry_unblock_queue on bhr_blockentry (unblock_at, ident, removed) where removed is null'),
    ]
